### ISSUE TITLE
Include adl fixes

### ISSUE THREAD

**Issue by wildchild** [Bufius/vertminer-gpu#1]
Excerpt from http://www.ohmpie.com/mining-on-an-r9-290-in-linux/

This means cgminer isn’t capable of handling the latest series of graphics cards.  The solution involves compiling cgminer from scratch and fixing the adl calls or just disabling anything related to temperature and fan control — a bad idea considering how hard mining is on video cards.  Its critical to monitor and control temps or risk destroying very expensive GPUs. So based on information attained here I went ahead and recompiled cgminer with the latest and greatest SDK and AMD drivers — it works perfectly now.  No more crashes on exit.

In the adl.c file around line 472, just before the ADL_Overdrive5_FanSpeed_Get call, add a line above:

```
ga->DefFanSpeedValue.iSpeedType=ADL_DL_FANCTRL_SPEED_TYPE_PERCENT;
```

**Comment by dureiken** [comment]
Hi
could you please add this fixe to your cgminer, I can't use my watercooled 290x.

Thanks a lot for your work

**Comment by Bufius** [comment]
done
