### ISSUE TITLE
Building in windows

### ISSUE THREAD

**Issue by knifesk** [Bufius/vertminer-gpu#10]
Is there any extra step needed to build in windows? I couldnt compile the source following the instructions in build-windows.txt

**Comment by knifesk** [comment]
I'll attach the error that mingw outputs.

libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:95: error: possibly undefined macro: AC_DEFINE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:185: error: possibly undefined macro: AC_MSG_ERROR
autoreconf: /usr/bin/autoconf-2.68 failed with exit status: 1

**Comment by Singman33** [comment]
I dont have that problem. I use theses commands :
autoreconf -fvi
CFLAGS="-O2 -msse2" ./configure --enable-opencl --enable-scrypt
make

To setup the build envirronement, I follow the instructions found on other miners, like https://github.com/prettyhatemachine/sph-sgminer/blob/master/doc/windows-build.txt

**Comment by knifesk** [comment]
Ohh, I see... I've just downloaded that synaptic-like new interface... Maybe that's wrong. I'll follow this guide instead from the top. Thanks. will post back results

**Comment by knifesk** [comment]
Yup.. worked like a charm.

**Comment by Singman33** [comment]
Cool, issue could be closed.

**Comment by knifesk** [comment]
Agreed. Thanks Singman
