### ISSUE TITLE
temperature and fan settings don't seem to work

### ISSUE THREAD

**Issue by Sinyk7** [Bufius/vertminer-gpu#4]
I ported vertminer into BAMT and i noticed that certain settings don't seem to work no matter what I put in my .conf file. Settings like temp-target or gpu-fan don't seem to get picked up by vertminer. Is this a bug? I really want to control my fans for the sake of the noise.

**Comment by VeNoMouS** [comment]
your missing ADL... put sdk headers in and recompile..

**Comment by Bufius** [comment]
use ADL headers and recompile
