### ISSUE TITLE
Without configure file

### ISSUE THREAD

**Issue by deanguan** [Bufius/vertminer-gpu#7]
While I follow http://vertcoin.org/gpu-miner-build-howto.html#mining to install wallet. Everything is fine, except the last step：./buildit.sh . The terminal msg below：

./buildit.sh: 2: ./buildit.sh: ./configure: not found
make: **\* No targets specified and no makefile found.  Stop.
./buildit.sh: 5: [: -a: unexpected operator
stripping vertminer
strip: vertminer：無此檔案

Then I trying to compile if by ./configure. There is no any configure file. How to install Vertcoin in Linux?

**Comment by jamesstout** [comment]
You may need to run ./autogen.sh

EDIT: or check out the 0.5.3 branch:

```
git checkout 0.5.3
```

**Comment by deanguan** [comment]
Hi, James. I download the zip file of 0.5.3 and extract it. It can be compiled. Thank you!
